# Generated by Django 4.0.4 on 2022-07-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accesorio_comidaperro_delete_comidaperros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idusuario', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID accesorio')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('nro_telefono', models.CharField(max_length=7)),
                ('contrasena', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='comidagatos',
        ),
        migrations.DeleteModel(
            name='comidaperros',
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='precio',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='comidagato',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comidagato',
            name='precio',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='comidaperro',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comidaperro',
            name='precio',
            field=models.CharField(max_length=7),
        ),
    ]
